<a href="https://colab.research.google.com/github/surajkale970-cmyk/ML121/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr = np.arange(0,11)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
arr[8]
arr[0:5]


array([0, 1, 2, 3, 4])

In [3]:
arr[0:5]=100
arr



array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [4]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [6]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [7]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [8]:
arr_copy = arr .copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [9]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [10]:
arr_2d[1]


array([20, 25, 30])

In [11]:
arr_2d[1] [0]

np.int64(20)

In [12]:
#2D array slicing
arr_2d[:2,1:]


array([[10, 15],
       [25, 30]])

In [13]:
arr_2d[2]

array([35, 40, 45])

In [14]:
arr_2d[2,:]


array([35, 40, 45])

In [17]:
#Fancy indexing
arr2d = np.zeros((10,10))
